spring.application.name=groups-service

# Server
server.forward-headers-strategy=framework
server.port=0

# Eureka
eureka.client.service-url.defaultZone=${EUREKA_DEFAULTZONE:http://localhost:8761/eureka}

# DB
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/groups_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

catalog.service.url=${CATALOG_URL:http://catalog-service}
